---
baseurl: "/"
defaultContentLanguage: fr
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
pluralizelisttitles: false

Languages:
  fr:
    weight: 1
    title: "Boris Schapira"
  en:
    weight: 2
    title: "Hi, I'm Boris"
    
theme: "bs-theme"
copyright: "&copy; Boris Schapira"

taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"

SectionPagesMenu: "main"

footnotereturnlinkcontents: "↩"
permalinks:
  default: "/:year/:month/:slug/"
  papa: "/:year/:month/:slug/"
  citoyen: "/:year/:month/:slug/"
paginatePath: ""

paginate: 5

googleAnalytics: "UA-4257717-9"

taxonomies:
  2005: "2005"
  2006: "2006"
  2007: "2007"
  2008: "2008"
  2009: "2009"
  2010: "2010"
  2011: "2011"
  2012: "2012"
  2013: "2013"
  2014: "2014"
  2015: "2015"
  2016: "2016"

params:
    highlight:
        style: "github"
        languages: ["go", "dockerfile"]
    social:
        - url: "https://github.com/borisschapira"
          fa_icon: "fa-github"
        - url: "https://twitter.com/borisschapira"
          fa_icon: "fa-twitter"
        - url: "/index.xml"
          fa_icon: "fa-rss"
---